### ISSUE TITLE
can you offer dataset?

### ISSUE THREAD

**Issue by WenChunTech** [tomerwul/CharLevelHyperNetworks#1]
i cant not find the dataset

**Comment by tomerwul** [comment]
Hi,

The MegaSpeech dataset, which includes 1M synthetic sequences, can be downloaded from:
[https://github.com/tomerwul/MegaSpeech](url)

One can generate additional sequences by following the generation process described at [https://ieeexplore.ieee.org/abstract/document/9238420](url)

**Comment by WenChunTech** [comment]
thanks
